if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif

set nocompatible " Use Vim defaults (much better!)
set bs=indent,eol,start  " allow backspacing over everything in insert mode
set ai   " always set autoindenting on
set nobackup  " keep a backup file
set viminfo='20,\"200 " read/write a .viminfo file, don't store more
   " than 50 lines of registers
set history=200  " keep 50 lines of command line history
set ruler  " show the cursor position all the time


filetype on
filetype plugin on
filetype indent on
set encoding=utf-8 
set fileencodings=ucs-bom,utf-8,latin1,chinese,latin-1
set noswapfile
set nu
set cursorline
syntax on
set tabstop=4
set smarttab
set shiftwidth=4
set autoindent
set mouse=a
set gfn=Courier\ 10\ Pitch\ 16
set expandtab
au BufRead,BufNewFile *.sv  set filetype=systemverilog
au BufRead,BufNewFile *.svh  set filetype=systemverilog
au BufRead,BufNewFile *.v  set filetype=systemverilog
au BufRead,BufNewFile *.V  set filetype=systemverilog
au BufRead,BufNewFile *.svi  set filetype=systemverilog
au BufRead,BufNewFile *.svp  set filetype=systemverilog
au BufRead,BufNewFile *.vp   set filetype=systemverilog
au BufRead,BufNewFile *.svq  set filetype=systemverilog
au BufRead,BufNewFile *.vq  set filetype=systemverilog
au BufRead,BufNewFile *.build  set filetype=python
au BufRead,BufNewFile *.list  set filetype=c
au BufRead,BufNewFile *.dump set filetype=tcl
"set guifont=Monospace\ 16
"set background=dark
colorscheme koehler
"colorscheme desert
"colorscheme molokai
let g:molokai_original = 1
let g:rehash256 = 1
function! CleverTab()
        let col=col('.')-1
        if !col || getline('.')[col-1] !~ '\k'
                return "\<TAB>"
        else
                return "\<C-N>"
        endif
endfunction
inoremap <Tab> <C-R>=CleverTab()<CR>

nmap <F2> :nohl<CR>
